language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t test-travis -f Dockerfile.dev .

script:
  - docker run -e CI=true test-travis npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-004444102354"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY